### Envoyer une requete POST pour créer un employee
POST  http://localhost:5001/employees/
Content-Type: application/json

{ "name": "Joseph", "password": "Joseph", "role":"Cashier" }



### Envoyer une requete POST pour créer un employee
POST  http://localhost:5001/employees/
Content-Type: application/json

{ "name": "Toscane", "password": "Toscane", "role":"Server" }


### Envoyer une requete POST pour créer un employee
POST  http://localhost:5001/employees/
Content-Type: application/json

{ "name": "Cyrille", "password": "Cyrille", "role":"Chief_of_resto" }


### Requete GET pour recevoir tous les employees GetALLEmployee
GET   http://localhost:5001/employees/
Content-Type: application/json

### Requete GET pour recevoir tous les employees GetEmployebyId
GET   http://localhost:5001/employees/d8cfbc6c-818d-49e4-8eaf-8a54a7e61999
Content-Type: application/json


### Requete pour SUPPRIMER tous les employees , uniquement par le chef_of_resto
DELETE  http://localhost:5001/employees/delete_all/eb64efe3-4708-4bbc-bcc1-a8d686cb40e5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImViNjRlZmUzLTQ3MDgtNGJiYy1iY2MxLWE4ZDY4NmNiNDBlNSIsImV4cCI6MTc2NDUwOTIxMH0.vtOA5zoe4N7jqxODHga-bEcYf7XhryaXI6zO7Bsj6vY


### Envoyer une requete POST pour créer une TASK
POST  http://localhost:5001/tasks/
Content-Type: application/json

{   "title": "Servir table",
    "content": "Servir table 3 ",
    "author_id": "eb64efe3-4708-4bbc-bcc1-a8d686cb40e5",
    "recipient_id": "fcd2dac9-ad84-4408-a97c-d96ffde30b99" }



### Update employee
PUT  http://localhost:5001/employees/updateme/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImZjZDJkYWM5LWFkODQtNDQwOC1hOTdjLWQ5NmZmZGUzMGI5OSIsImV4cCI6MTc2NDcxNTIyMH0.ZXUusj_U9eQb25UBP7FiAcpPYFYMm8zOA8iN35U-gBo
Content-Type: application/json

{"name": "Joseph_update3" , "password": "Joseph_update3", "role":"Cook" }



### Créer token
POST http://localhost:5001/auth/token/
Content-Type: application/json

{ "name": "Joseph", "password": "Joseph", "role":"Cashier" }


### DEL A TASK
DELETE  http://localhost:5001/tasks/deltask/c826bc94-6978-40a9-8c5a-3492d53ca6f3
Content-Type: application/json


### GET TASKS by recipient id
GET   http://localhost:5001/tasks/taskrecipient/fcd2dac9-ad84-4408-a97c-d96ffde30b99
Content-Type: application/json


### Requete pour SUPPRIMER toutes les tasks , uniquement par le chef_of_resto
DELETE  http://localhost:5001/tasks/deletealltask/fcd2dac9-ad84-4408-a97c-d96ffde30b99
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImViNjRlZmUzLTQ3MDgtNGJiYy1iY2MxLWE4ZDY4NmNiNDBlNSIsImV4cCI6MTc2NDc0MDE2MX0.TB-T3_Y2DdfpFU9Ul5ZmXH4a0wDcgnnywxCGNDG1Dxc








