### Envoyer une requete POST pour créer un employee
POST  http://localhost:5001/employees/
Content-Type: application/json

{ "name": "Joseph", "password": "Joseph", "role":"Cashier" }



### Envoyer une requete POST pour créer un employee
POST  http://localhost:5001/employees/
Content-Type: application/json

{ "name": "Toscane", "password": "Toscane", "role":"Server" }


### Envoyer une requete POST pour créer un employee
POST  http://localhost:5001/employees/
Content-Type: application/json

{ "name": "Cyrille", "password": "Cyrille", "role":"Chief_of_resto" }


### Requete GET pour recevoir tous les employees GetALLEmployee
GET   http://localhost:5001/employees/
Content-Type: application/json

### Requete GET pour recevoir tous les employees GetEmployebyId
GET   http://localhost:5001/employees/d8cfbc6c-818d-49e4-8eaf-8a54a7e61999
Content-Type: application/json


### Requete pour SUPPRIMER tous les employees , uniquement par le chef_of_resto
DELETE  http://localhost:5001/employees/delete_all/eb64efe3-4708-4bbc-bcc1-a8d686cb40e5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImViNjRlZmUzLTQ3MDgtNGJiYy1iY2MxLWE4ZDY4NmNiNDBlNSIsImV4cCI6MTc2NDUwOTIxMH0.vtOA5zoe4N7jqxODHga-bEcYf7XhryaXI6zO7Bsj6vY


### Envoyer une requete POST pour créer une TASK
POST  http://localhost:5001/tasks/
Content-Type: application/json

{   "title": "Servir table",
    "content": "Servir table 3 ",
    "author_id": "37c4565d-c612-49cb-91f0-bcf647ab8c3f",
    "recipient_id": "30b9a37a-8d0d-45cc-ab5c-70ec975a7cc6" }




### Update employee
PUT  http://localhost:5001/employees/updateme/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImFlZjdhYjIxLTI5MDUtNGI4MC1iNmMzLWQ5ZWZkNjEzMzRhYyIsImV4cCI6MTc2NDUxNTc1MX0.R1hyP8MRRNjOrE6-s7HT0X8ttshfKiNCtJiEeHoJKIc
Content-Type: application/json

{"name": "Joseph_update3" , "password": "Joseph_update3", "role":"Cook" }



### Créer token
POST http://localhost:5001/auth/token/
Content-Type: application/json

{ "name": "Joseph", "password": "Joseph", "role":"Cashier" }



